# =============================
#        ChatColors Plugin
# =============================
# The plugin.yml file defines essential metadata and configurations for the ChatColors plugin.

name: ChatColor                        # The name of your plugin
version: 1.0                           # Plugin version
main: org.mythofy.chatcolors.ChatColorsPlugin  # Fully qualified main class path
api-version: 1.21                      # The Minecraft version the plugin targets

# ---------------------------------------------------------------------
# Commands Configuration
# ---------------------------------------------------------------------
commands:
  chatcolor:
    description: Change your chat color            # Brief description of the command
    usage: /<command> [color]                      # Usage instructions
    permission: chatcolor.use                      # Permission node required to execute the command
    permission-message: "You do not have permission to use chat colors."  # Message displayed if permission is denied

# ---------------------------------------------------------------------
# Permissions Configuration
# ---------------------------------------------------------------------
permissions:
  chatcolor.use:
    description: Allows the use of the /chatcolor command
    default: true                                  # Default permission level (true means everyone can use it by default)

  chatcolor.red:
    description: Allows the use of the red chat color
    default: false                                 # Default to false; needs to be granted to players/groups

  chatcolor.blue:
    description: Allows the use of the blue chat color
    default: false

  chatcolor.green:
    description: Allows the use of the green chat color
    default: false

  chatcolor.gold:
    description: Allows the use of the gold chat color
    default: false

  chatcolor.purple:
    description: Allows the use of the purple chat color
    default: false

  chatcolor.custom:
    description: Allows the use of the custom chat color
    default: false

  chatcolor.gradient:
    description: Allows the use of gradient chat colors
    default: false

  chatcolor.rainbow:
    description: Allows the use of rainbow chat colors
    default: false

